Panel result csv
skriyaz95/goal-gene-panel-search pull request #31
Opened 2021-08-27 17:24 UTC by skriyaz95

2021-08-27 17:48 UTC, cmonnom requested changes
Looks good. Simplify the for loop and rename the download button and that should do the trick.

2021-08-27 17:48 UTC, cmonnom commented on src/components/home/PanelResult.vue
> +        <v-btn class="primary" @click="downloadGenes(panelName, panelGenes)">
Let's rename the button 'Download' and add a download icon on the righthand side like the buttons in Manage

2021-08-27 17:48 UTC, cmonnom commented on src/components/home/PanelResult.vue
> +      while(i++ <= genesInPanel.length && j++ <= genesNotInPanel.length) {
This is a bit convoluted. Instead, you could either check which list is the longest and check whether a value is undefined (because you've reach the end of the shortest list) and push '' in that situation, or you could use the transpose function in utils/arrays.ts which will do the work of transposing the rows (found and notFound) into columns.

2021-08-28 00:41 UTC, skriyaz95 commented on src/components/home/PanelResult.vue
> +      while(i++ <= genesInPanel.length && j++ <= genesNotInPanel.length) {
done

2021-08-28 00:41 UTC, skriyaz95 commented on src/components/home/PanelResult.vue
> +        <v-btn class="primary" @click="downloadGenes(panelName, panelGenes)">
done

2021-08-28 00:41 UTC, merged